# Generated by Django 4.2.4 on 2023-10-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_product_pname_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a_price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
