# Generated by Django 4.2.4 on 2023-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='R_password',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
