# Generated by Django 4.2.4 on 2023-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_customer_r_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
