# Generated by Django 4.2.4 on 2023-10-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_product_pname_product_price'),
        ('projectapp', '0003_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.product')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.customer')),
            ],
        ),
    ]
