# Generated by Django 4.2.4 on 2023-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='', upload_to='product/')),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
