# Generated by Django 4.2.4 on 2023-10-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile_image',
        ),
    ]
