# Generated by Django 4.2.4 on 2023-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_remove_order_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
