# Generated by Django 4.2.4 on 2023-10-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AddField(
            model_name='order',
            name='register',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projectapp.customer'),
        ),
    ]
