# Generated by Django 4.2.4 on 2023-10-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_order_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='projectapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
