# Generated by Django 4.2.4 on 2023-10-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_alter_order_register_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tot_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_no',
            field=models.IntegerField(max_length=200),
        ),
    ]
