# Generated by Django 4.2.4 on 2023-10-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_cart_tot_price_alter_order_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
