# Generated by Django 4.2.4 on 2023-10-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_alter_order_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tot_price',
        ),
    ]
