# Generated by Django 4.2.4 on 2023-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_remove_cart_tot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tot_price',
            field=models.IntegerField(default=0),
        ),
    ]
